### ISSUE TITLE
Initial thoughts on limiting spawning

### ISSUE THREAD

**Issue by ApolloX939** [pl608/ctf_airplane_extras#1]
My initial thoughts on limiting plane spawning is rather quite simply a cooldown.

Use a node timer to wait a period of time before another plane can be spawned, while it doesn't directly stop excess of planes being spawned it does slow the process down, and adds a little bit of a ability like flavor to it. (Making planes more valued)

A good approach I'd do is use infotext to show the current status of the cooldown, where each second is reduced from the total cooldown time and updates the infotext.

I.E. "Red Plane Spawn (14)" to indicated a red plane and one can be requested in 14 seconds.

**Comment by pl608** [comment]
Actually might do that. Just need to get the on_click spawning working

**Comment by pl608** [comment]
I think i got it working
only thing is is that it uses an abm instead of a node timer
